spring.servlet:
  multipart:
    max-file-size: 30MB
    max-request-size: 30MB

server.compression:
  enabled: true

image.storage:
  root-directory: static/images

security:
  authorization-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

cache:
  max-age: 600 # 최대 값: 31536000 (1년)

---

spring:
  config.activate.on-profile: prod
security:
  authorization-key: ${SECRET_KEY}
