spring.servlet:
  multipart:
    max-file-size: 30MB
    max-request-size: 30MB

image.storage:
  root-directory: static/images
security:
  authorization-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

---

spring:
  config.activate.on-profile: prod
security:
  authorization-key: ${SECRET_KEY}
